CREATE DATABASE BBSQLitedb;

USE BBSQLitedb;


CREATE TABLE IF NOT EXISTS 'Players' (
  'pid' int NOT NULL,
  'name' varchar NOT NULL,
  PRIMARY KEY ('pid')
);


CREATE TABLE IF NOT EXISTS 'PerGame' (
  'pid' int NOT NULL,
  'year' int NOT NULL,
  'age' int NOT NULL,
  'team' varchar NOT NULL,
  'position' varchar NOT NULL,
  'GP' int DEFAULT NULL,
  'GS'int DEFAULT NULL,
  'MP'real DEFAULT NULL,
  'FG'real DEFAULT NULL,
  'FGA'real DEFAULT NULL,
  'FG%'real DEFAULT NULL,
  '3P'real DEFAULT NULL,
  '3PA'real DEFAULT NULL,
  '3P%'real DEFAULT NULL,
  '2P'real DEFAULT NULL,
  '2PA'real DEFAULT NULL,
  '2P%'real DEFAULT NULL,
  'EFG%'real DEFAULT NULL,
  'FT'real DEFAULT NULL,
  'FTA'real DEFAULT NULL,
  'FT%'real DEFAULT NULL,
  'ORB'real DEFAULT NULL,
  'DRB'real DEFAULT NULL,
  'TRB'real DEFAULT NULL,
  'AST'real DEFAULT NULL,
  'STL'real DEFAULT NULL,
  'BLK'real DEFAULT NULL,
  'TOV'real DEFAULT NULL,
  'PF'real DEFAULT NULL,
  'PTS'real DEFAULT NULL,
  PRIMARY KEY ('pid', 'year', 'team')
);


CREATE TABLE IF NOT EXISTS 'Totals' (
  'pid' int NOT NULL,
  'year' int NOT NULL,
  'age' int NOT NULL,
  'team' varchar NOT NULL,
  'position' varchar NOT NULL,
  'GP' int DEFAULT NULL,
  'GS'int DEFAULT NULL,
  'MP'int DEFAULT NULL,
  'FG'int DEFAULT NULL,
  'FGA'int DEFAULT NULL,
  'FG%'real DEFAULT NULL,
  '3P'int DEFAULT NULL,
  '3PA'int DEFAULT NULL,
  '3P%'real DEFAULT NULL,
  '2P'int DEFAULT NULL,
  '2PA'int DEFAULT NULL,
  '2P%'real DEFAULT NULL,
  'EFG%'real DEFAULT NULL,
  'FT'int DEFAULT NULL,
  'FTA'int DEFAULT NULL,
  'FT%'real DEFAULT NULL,
  'ORB'int DEFAULT NULL,
  'DRB'int DEFAULT NULL,
  'TRB'int DEFAULT NULL,
  'AST'int DEFAULT NULL,
  'STL'int DEFAULT NULL,
  'BLK'int DEFAULT NULL,
  'TOV'int DEFAULT NULL,
  'PF'int DEFAULT NULL,
  'PTS'int DEFAULT NULL,
  PRIMARY KEY ('pid', 'year', 'team')
);


CREATE TABLE IF NOT EXISTS 'Per36' (
  'pid' int NOT NULL,
  'year' int NOT NULL,
  'age' int NOT NULL,
  'team' varchar NOT NULL,
  'position' varchar NOT NULL,
  'GP' int DEFAULT NULL,
  'GS'int DEFAULT NULL,
  'MP'int DEFAULT NULL,
  'FG'real DEFAULT NULL,
  'FGA'real DEFAULT NULL,
  'FG%'real DEFAULT NULL,
  '3P'real DEFAULT NULL,
  '3PA'real DEFAULT NULL,
  '3P%'real DEFAULT NULL,
  '2P'real DEFAULT NULL,
  '2PA'real DEFAULT NULL,
  '2P%'real DEFAULT NULL,
  'EFG%'real DEFAULT NULL,
  'FT'real DEFAULT NULL,
  'FTA'real DEFAULT NULL,
  'FT%'real DEFAULT NULL,
  'ORB'real DEFAULT NULL,
  'DRB'real DEFAULT NULL,
  'TRB'real DEFAULT NULL,
  'AST'real DEFAULT NULL,
  'STL'real DEFAULT NULL,
  'BLK'real DEFAULT NULL,
  'TOV'real DEFAULT NULL,
  'PF'real DEFAULT NULL,
  'PTS'real DEFAULT NULL,
  PRIMARY KEY ('pid', 'year', 'team')
);


CREATE TABLE IF NOT EXISTS 'Per100Poss' (
  'pid' int NOT NULL,
  'year' int NOT NULL,
  'age' int NOT NULL,
  'team' varchar NOT NULL,
  'position' varchar NOT NULL,
  'GP' int DEFAULT NULL,
  'GS'int DEFAULT NULL,
  'MP'int DEFAULT NULL,
  'FG'real DEFAULT NULL,
  'FGA'real DEFAULT NULL,
  'FG%'real DEFAULT NULL,
  '3P'real DEFAULT NULL,
  '3PA'real DEFAULT NULL,
  '3P%'real DEFAULT NULL,
  '2P'real DEFAULT NULL,
  '2PA'real DEFAULT NULL,
  '2P%'real DEFAULT NULL,
  'FT'real DEFAULT NULL,
  'FTA'real DEFAULT NULL,
  'FT%'real DEFAULT NULL,
  'ORB'real DEFAULT NULL,
  'DRB'real DEFAULT NULL,
  'TRB'real DEFAULT NULL,
  'AST'real DEFAULT NULL,
  'STL'real DEFAULT NULL,
  'BLK'real DEFAULT NULL,
  'TOV'real DEFAULT NULL,
  'PF'real DEFAULT NULL,
  'PTS'real DEFAULT NULL,
  'ORTG' int DEFAULT NULL,
  'DRTG' int DEFAULT NULL,
  PRIMARY KEY ('pid', 'year', 'team')
);


CREATE TABLE IF NOT EXISTS 'Advanced' (
  'pid' int NOT NULL,
  'year' int NOT NULL,
  'age' int NOT NULL,
  'team' varchar NOT NULL,
  'position' varchar NOT NULL,
  'GP' int DEFAULT NULL,
  'MP'int DEFAULT NULL,
  'PER' real DEFAULT NULL,
  'TS%' real DEFAULT NULL,
  '3PAR' real DEFAULT NULL,
  'FTR' real DEFAULT NULL,
  'ORB%' real DEFAULT NULL,
  'DRB%' real DEFAULT NULL,
  'TRB%' real DEFAULT NULL,
  'AST%' real DEFAULT NULL,
  'STL%' real DEFAULT NULL,
  'BLK%' real DEFAULT NULL,
  'TOV%' real DEFAULT NULL,
  'USG%' real DEFAULT NULL,
  'OWS' real DEFAULT NULL,
  'DWS' real DEFAULT NULL,
  'WS' real DEFAULT NULL,
  'WS/48' real DEFAULT NULL,
  'OBPM' real DEFAULT NULL,
  'DBPM' real DEFAULT NULL,
  'BPM' real DEFAULT NULL,
  'VORP' real DEFAULT NULL,
  PRIMARY KEY ('pid', 'year', 'team')
);

CREATE TABLE IF NOT EXISTS 'Shooting' (
  'pid' int NOT NULL,
  'year' int NOT NULL,
  'age' int NOT NULL,
  'team' varchar NOT NULL,
  'position' varchar NOT NULL,
  'GP' int DEFAULT NULL,
  'MP'int DEFAULT NULL,
  'FG%'real DEFAULT NULL,
  'DIST'real DEFAULT NULL,
  '2P%ofFGBD'real DEFAULT NULL,
  '0-3%ofFGBD'real DEFAULT NULL,
  '3-10%ofFGBD'real DEFAULT NULL,
  '10-16%ofFGBD'real DEFAULT NULL,
  '16-3PT%ofFGBD'real DEFAULT NULL,
  '3P%ofFGBD'real DEFAULT NULL,
  '2PFG%BD'real DEFAULT NULL,
  '0-3FG%BD'real DEFAULT NULL,
  '3-10FG%BD'real DEFAULT NULL,
  '10-16FG%BD'real DEFAULT NULL,
  '16-3PTFG%BD'real DEFAULT NULL,
  '3PFG%BD'real DEFAULT NULL,
  'D%ASTD' real DEFAULT NULL,
  'D%FGA' real DEFAULT NULL,
  'DMD' int DEFAULT NULL,
  '3%ASTD' real DEFAULT NULL,
  '3%3PA' real DEFAULT NULL,
  '3P%' real DEFAULT NULL,
  '3ATT' int DEFAULT NULL,
  '3MD' int DEFAULT NULL,
  PRIMARY KEY ('pid', 'year', 'team')
);


CREATE TABLE IF NOT EXISTS 'PlayByPlay' (
  'pid' int NOT NULL,
  'year' int NOT NULL,
  'age' int NOT NULL,
  'team' varchar NOT NULL,
  'position' varchar NOT NULL,
  'GP' int DEFAULT NULL,
  'MP' int DEFAULT NULL,
  'PG%' int DEFAULT NULL,
  'SG%' int DEFAULT NULL,
  'SF%' int DEFAULT NULL,
  'PF%' int DEFAULT NULL,
  'C%' int DEFAULT NULL,
  'OnCourt' real DEFAULT NULL,
  'OnOff' real DEFAULT NULL,
  'BadPass' int DEFAULT NULL,
  'LostPass' int DEFAULT NULL,
  'FCShoot' int DEFAULT NULL,
  'FCOff' int DEFAULT NULL,
  'FDShoot' int DEFAULT NULL,
  'FDOff' int DEFAULT NULL,
  'PGA' int DEFAULT NULL,
  'And1' int DEFAULT NULL,
  'Blkd' int DEFAULT NULL,
  PRIMARY KEY ('pid', 'year', 'team')
);


CREATE TABLE IF NOT EXISTS 'PlayoffPerGame' (
  'pid' int NOT NULL,
  'year' int NOT NULL,
  'age' int NOT NULL,
  'team' varchar NOT NULL,
  'position' varchar NOT NULL,
  'GP' int DEFAULT NULL,
  'GS'int DEFAULT NULL,
  'MP'real DEFAULT NULL,
  'FG'real DEFAULT NULL,
  'FGA'real DEFAULT NULL,
  'FG%'real DEFAULT NULL,
  '3P'real DEFAULT NULL,
  '3PA'real DEFAULT NULL,
  '3P%'real DEFAULT NULL,
  '2P'real DEFAULT NULL,
  '2PA'real DEFAULT NULL,
  '2P%'real DEFAULT NULL,
  'EFG%'real DEFAULT NULL,
  'FT'real DEFAULT NULL,
  'FTA'real DEFAULT NULL,
  'FT%'real DEFAULT NULL,
  'ORB'real DEFAULT NULL,
  'DRB'real DEFAULT NULL,
  'TRB'real DEFAULT NULL,
  'AST'real DEFAULT NULL,
  'STL'real DEFAULT NULL,
  'BLK'real DEFAULT NULL,
  'TOV'real DEFAULT NULL,
  'PF'real DEFAULT NULL,
  'PTS'real DEFAULT NULL,
  PRIMARY KEY ('pid', 'year', 'team')
);


CREATE TABLE IF NOT EXISTS 'PlayoffTotals' (
  'pid' int NOT NULL,
  'year' int NOT NULL,
  'age' int NOT NULL,
  'team' varchar NOT NULL,
  'position' varchar NOT NULL,
  'GP' int DEFAULT NULL,
  'GS'int DEFAULT NULL,
  'MP'int DEFAULT NULL,
  'FG'int DEFAULT NULL,
  'FGA'int DEFAULT NULL,
  'FG%'real DEFAULT NULL,
  '3P'int DEFAULT NULL,
  '3PA'int DEFAULT NULL,
  '3P%'real DEFAULT NULL,
  '2P'int DEFAULT NULL,
  '2PA'int DEFAULT NULL,
  '2P%'real DEFAULT NULL,
  'EFG%'real DEFAULT NULL,
  'FT'int DEFAULT NULL,
  'FTA'int DEFAULT NULL,
  'FT%'real DEFAULT NULL,
  'ORB'int DEFAULT NULL,
  'DRB'int DEFAULT NULL,
  'TRB'int DEFAULT NULL,
  'AST'int DEFAULT NULL,
  'STL'int DEFAULT NULL,
  'BLK'int DEFAULT NULL,
  'TOV'int DEFAULT NULL,
  'PF'int DEFAULT NULL,
  'PTS'int DEFAULT NULL,
  PRIMARY KEY ('pid', 'year', 'team')
);


CREATE TABLE IF NOT EXISTS 'PlayoffPer36' (
  'pid' int NOT NULL,
  'year' int NOT NULL,
  'age' int NOT NULL,
  'team' varchar NOT NULL,
  'position' varchar NOT NULL,
  'GP' int DEFAULT NULL,
  'GS'int DEFAULT NULL,
  'MP'int DEFAULT NULL,
  'FG'real DEFAULT NULL,
  'FGA'real DEFAULT NULL,
  'FG%'real DEFAULT NULL,
  '3P'real DEFAULT NULL,
  '3PA'real DEFAULT NULL,
  '3P%'real DEFAULT NULL,
  '2P'real DEFAULT NULL,
  '2PA'real DEFAULT NULL,
  '2P%'real DEFAULT NULL,
  'EFG%'real DEFAULT NULL,
  'FT'real DEFAULT NULL,
  'FTA'real DEFAULT NULL,
  'FT%'real DEFAULT NULL,
  'ORB'real DEFAULT NULL,
  'DRB'real DEFAULT NULL,
  'TRB'real DEFAULT NULL,
  'AST'real DEFAULT NULL,
  'STL'real DEFAULT NULL,
  'BLK'real DEFAULT NULL,
  'TOV'real DEFAULT NULL,
  'PF'real DEFAULT NULL,
  'PTS'real DEFAULT NULL,
  PRIMARY KEY ('pid', 'year', 'team')
);


CREATE TABLE IF NOT EXISTS 'PlayoffPer100Poss' (
  'pid' int NOT NULL,
  'year' int NOT NULL,
  'age' int NOT NULL,
  'team' varchar NOT NULL,
  'position' varchar NOT NULL,
  'GP' int DEFAULT NULL,
  'GS'int DEFAULT NULL,
  'MP'int DEFAULT NULL,
  'FG'real DEFAULT NULL,
  'FGA'real DEFAULT NULL,
  'FG%'real DEFAULT NULL,
  '3P'real DEFAULT NULL,
  '3PA'real DEFAULT NULL,
  '3P%'real DEFAULT NULL,
  '2P'real DEFAULT NULL,
  '2PA'real DEFAULT NULL,
  '2P%'real DEFAULT NULL,
  'FT'real DEFAULT NULL,
  'FTA'real DEFAULT NULL,
  'FT%'real DEFAULT NULL,
  'ORB'real DEFAULT NULL,
  'DRB'real DEFAULT NULL,
  'TRB'real DEFAULT NULL,
  'AST'real DEFAULT NULL,
  'STL'real DEFAULT NULL,
  'BLK'real DEFAULT NULL,
  'TOV'real DEFAULT NULL,
  'PF'real DEFAULT NULL,
  'PTS'real DEFAULT NULL,
  'ORTG' int DEFAULT NULL,
  'DRTG' int DEFAULT NULL,
  PRIMARY KEY ('pid', 'year', 'team')
);


CREATE TABLE IF NOT EXISTS 'PlayoffAdvanced' (
  'pid' int NOT NULL,
  'year' int NOT NULL,
  'age' int NOT NULL,
  'team' varchar NOT NULL,
  'position' varchar NOT NULL,
  'GP' int DEFAULT NULL,
  'MP'int DEFAULT NULL,
  'PER' real DEFAULT NULL,
  'TS%' real DEFAULT NULL,
  '3PAR' real DEFAULT NULL,
  'FTR' real DEFAULT NULL,
  'ORB%' real DEFAULT NULL,
  'DRB%' real DEFAULT NULL,
  'TRB%' real DEFAULT NULL,
  'AST%' real DEFAULT NULL,
  'STL%' real DEFAULT NULL,
  'BLK%' real DEFAULT NULL,
  'TOV%' real DEFAULT NULL,
  'USG%' real DEFAULT NULL,
  'OWS' real DEFAULT NULL,
  'DWS' real DEFAULT NULL,
  'WS' real DEFAULT NULL,
  'WS/48' real DEFAULT NULL,
  'OBPM' real DEFAULT NULL,
  'DBPM' real DEFAULT NULL,
  'BPM' real DEFAULT NULL,
  'VORP' real DEFAULT NULL,
  PRIMARY KEY ('pid', 'year', 'team')
);

CREATE TABLE IF NOT EXISTS 'PlayoffShooting' (
  'pid' int NOT NULL,
  'year' int NOT NULL,
  'age' int NOT NULL,
  'team' varchar NOT NULL,
  'position' varchar NOT NULL,
  'GP' int DEFAULT NULL,
  'MP'int DEFAULT NULL,
  'FG%'real DEFAULT NULL,
  'DIST'real DEFAULT NULL,
  '2P%ofFGBD'real DEFAULT NULL,
  '0-3%ofFGBD'real DEFAULT NULL,
  '3-10%ofFGBD'real DEFAULT NULL,
  '10-16%ofFGBD'real DEFAULT NULL,
  '16-3PT%ofFGBD'real DEFAULT NULL,
  '3P%ofFGBD'real DEFAULT NULL,
  '2PFG%BD'real DEFAULT NULL,
  '0-3FG%BD'real DEFAULT NULL,
  '3-10FG%BD'real DEFAULT NULL,
  '10-16FG%BD'real DEFAULT NULL,
  '16-3PTFG%BD'real DEFAULT NULL,
  '3PFG%BD'real DEFAULT NULL,
  'D%ASTD' real DEFAULT NULL,
  'D%FGA' real DEFAULT NULL,
  'DMD' int DEFAULT NULL,
  '3%ASTD' real DEFAULT NULL,
  '3%3PA' real DEFAULT NULL,
  '3P%' real DEFAULT NULL,
  '3ATT' int DEFAULT NULL,
  '3MD' int DEFAULT NULL,
  PRIMARY KEY ('pid', 'year', 'team')
);


CREATE TABLE IF NOT EXISTS 'PlayoffPlayByPlay' (
  'pid' int NOT NULL,
  'year' int NOT NULL,
  'age' int NOT NULL,
  'team' varchar NOT NULL,
  'position' varchar NOT NULL,
  'GP' int DEFAULT NULL,
  'MP' int DEFAULT NULL,
  'PG%' int DEFAULT NULL,
  'SG%' int DEFAULT NULL,
  'SF%' int DEFAULT NULL,
  'PF%' int DEFAULT NULL,
  'C%' int DEFAULT NULL,
  'OnCourt' real DEFAULT NULL,
  'OnOff' real DEFAULT NULL,
  'BadPass' int DEFAULT NULL,
  'LostPass' int DEFAULT NULL,
  'FCShoot' int DEFAULT NULL,
  'FCOff' int DEFAULT NULL,
  'FDShoot' int DEFAULT NULL,
  'FDOff' int DEFAULT NULL,
  'PGA' int DEFAULT NULL,
  'And1' int DEFAULT NULL,
  'Blkd' int DEFAULT NULL,
  PRIMARY KEY ('pid', 'year', 'team')
);


CREATE TABLE IF NOT EXISTS 'Contract' (
  'pid' int NOT NULL,
  'team' varchar NOT NULL,
  'year' int NOT NULL,
  'salary' int NOT NULL,
  PRIMARY KEY ('pid', 'year', 'team')
);
